# Generated by Django 5.2.1 on 2026-04-05 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('subtitle_source', models.CharField(choices=[('cc', 'Official CC'), ('auto', 'Auto-generated')], default='auto', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('segment_count', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictation_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DictationSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('transcript', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='dictation.dictationvideo')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('video', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DictationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('score', models.FloatField()),
                ('revealed_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_attempts', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='dictation.dictationsegment')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'segment'], name='dictation_d_user_id_13cd8d_idx'), models.Index(fields=['user', 'created_at'], name='dictation_d_user_id_26b8fd_idx')],
            },
        ),
    ]
