# Generated by Django 5.2.1 on 2026-04-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0002_quiz_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoquiz',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='dictation.dictationvideo'),
        ),
    ]
