from django.utils import translation

def manual_translations(request):
    """Manual translation context processor as fallback"""
    current_lang = translation.get_language()
    
    translations = {
        'en': {
            'learn_english': 'Learn English',
            'home': 'Home',
            'flashcards': 'Flashcards',
            'add_word': 'Add Word',
            'study': 'Study',
            'statistics': 'Statistics',
            'dashboard': 'Dashboard',
            'welcome_message': 'Welcome to LearnEnglish',
            'platform_description': 'Your personal vocabulary learning platform',
            'total_cards': 'Total Cards',
            'recent_cards': 'Recent Cards',
            'progress': 'Progress',
            'add_new_words': 'Add New Words',
            'study_cards': 'Study Cards',
            'add_flashcard': 'Add Flashcard',
            'add_new_flashcard': 'Add New Flashcard',
            'add_vocabulary_description': 'Add new vocabulary to your collection',
            'my_flashcards': 'My Flashcards',
            'vocabulary_collection': 'Your vocabulary collection',
            # Authentication texts
            'login_title': 'Login',
            'signup_title': 'Sign Up',
            'welcome_back': 'Welcome back!',
            'login_subtitle': 'Sign in to your account',
            'create_account': 'Create Account',
            'signup_subtitle': 'Start your vocabulary learning journey',
            'login_with_google': 'Sign in with Google',
            'signup_with_google': 'Sign up with Google',
            'or': 'or',
            'email_address': 'Email address',
            'password': 'Password',
            'confirm_password': 'Confirm password',
            'remember_me': 'Remember me',
            'forgot_password': 'Forgot password?',
            'sign_in': 'Sign in',
            'sign_up': 'Sign up',
            'dont_have_account': "Don't have an account?",
            'already_have_account': 'Already have an account?',
            'email_verification_notice': 'We will send you a verification email to activate your account.',
            'logout': 'Logout',
            'profile': 'Profile',
            # Decks
            'my_decks': 'My Decks',
            'back_to_all_decks': 'Back to all decks',
            # Statistics
            'statistics_title': 'Statistics',
            'total_decks': 'Total Decks',
            'average_cards_per_deck': 'Average Cards per Deck',
            'cards_per_deck': 'Cards per Deck',
            'no_decks_message': 'You have no decks yet.',
            # Study labels
            'start_study': 'Start Study',
            'select_decks': 'Select decks to study',
            'no_cards_due': 'No cards due for review today.',
            'grade_again': 'Again',
            'grade_hard': 'Hard',
            'grade_good': 'Good',
            'grade_easy': 'Easy',
            'show_answer': 'Show Answer',
            'mode_multiple_choice': 'Multiple Choice',
            'mode_type_answer': 'Type Answer',
            'select_mode': 'Select study mode',
            'check': 'Check',
            'correct': 'Correct!',
            'incorrect': 'Incorrect',
            'answer_placeholder': 'Type your answer...',
            'study_complete_title': 'Great job!',
            'study_complete_text': 'You have reviewed all due cards.',
            'next_card': 'Next Card →',
        },
        'vi': {
            'learn_english': 'Học Tiếng Anh',
            'home': 'Trang chủ',
            'flashcards': 'Thẻ từ vựng',
            'add_word': 'Thêm từ',
            'study': 'Học tập',
            'statistics': 'Thống kê',
            'dashboard': 'Bảng điều khiển',
            'welcome_message': 'Chào mừng đến với LearnEnglish',
            'platform_description': 'Nền tảng học từ vựng cá nhân của bạn',
            'total_cards': 'Tổng số thẻ',
            'recent_cards': 'Thẻ gần đây',
            'progress': 'Tiến độ',
            'add_new_words': 'Thêm từ mới',
            'study_cards': 'Học thẻ từ',
            'add_flashcard': 'Thêm Flashcard',
            'add_new_flashcard': 'Thêm Flashcard Mới',
            'add_vocabulary_description': 'Thêm từ vựng mới vào bộ sưu tập của bạn',
            'my_flashcards': 'Thẻ từ vựng của tôi',
            'vocabulary_collection': 'Bộ sưu tập từ vựng của bạn',
            # Authentication texts
            'login_title': 'Đăng nhập',
            'signup_title': 'Đăng ký',
            'welcome_back': 'Chào mừng trở lại!',
            'login_subtitle': 'Đăng nhập vào tài khoản của bạn',
            'create_account': 'Tạo tài khoản',
            'signup_subtitle': 'Bắt đầu hành trình học từ vựng',
            'login_with_google': 'Đăng nhập với Google',
            'signup_with_google': 'Đăng ký với Google',
            'or': 'hoặc',
            'email_address': 'Địa chỉ email',
            'password': 'Mật khẩu',
            'confirm_password': 'Xác nhận mật khẩu',
            'remember_me': 'Ghi nhớ đăng nhập',
            'forgot_password': 'Quên mật khẩu?',
            'sign_in': 'Đăng nhập',
            'sign_up': 'Đăng ký',
            'dont_have_account': 'Chưa có tài khoản?',
            'already_have_account': 'Đã có tài khoản?',
            'email_verification_notice': 'Chúng tôi sẽ gửi email xác thực để kích hoạt tài khoản của bạn.',
            'logout': 'Đăng xuất',
            'profile': 'Hồ sơ',
            # Decks
            'my_decks': 'Các bộ thẻ',
            'back_to_all_decks': 'Quay lại tất cả bộ thẻ',
            # Statistics
            'statistics_title': 'Thống kê',
            'total_decks': 'Tổng số bộ thẻ',
            'average_cards_per_deck': 'Số thẻ trung bình mỗi bộ',
            'cards_per_deck': 'Số thẻ trong mỗi bộ',
            'no_decks_message': 'Bạn chưa có bộ thẻ nào.',
            # Study labels
            'start_study': 'Bắt đầu ôn',
            'select_decks': 'Chọn bộ thẻ để ôn',
            'no_cards_due': 'Hôm nay không có thẻ cần ôn.',
            'grade_again': 'Làm lại',
            'grade_hard': 'Khó',
            'grade_good': 'Tốt',
            'grade_easy': 'Dễ',
            'show_answer': 'Hiện đáp án',
            'mode_multiple_choice': 'Trắc nghiệm',
            'mode_type_answer': 'Gõ đáp án',
            'select_mode': 'Chọn chế độ học',
            'check': 'Kiểm tra',
            'correct': 'Chính xác!',
            'incorrect': 'Chưa đúng',
            'answer_placeholder': 'Nhập đáp án...',
            'study_complete_title': 'Hoàn thành!',
            'study_complete_text': 'Bạn đã ôn xong tất cả thẻ cần ôn.',
            'next_card': 'Thẻ tiếp theo →',
        }
    }
    
    return {
        'manual_texts': translations.get(current_lang, translations['en']),
        'current_language_code': current_lang
    } 