# Generated by Django 4.2.23 on 2025-07-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_images/'),
        ),
        migrations.DeleteModel(
            name='Pronunciation',
        ),
    ]
