# Generated by Django 5.1.7 on 2025-07-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_flashcard_audio_url_flashcard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='related_image_url',
            field=models.URLField(blank=True, help_text='Auto-fetched related image URL', max_length=500, null=True),
        ),
    ]
