# Generated by Django 4.2.23 on 2025-07-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_flashcard_related_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='phonetic',
            field=models.CharField(blank=True, help_text='Phonetic transcription (e.g., /rɪˈzɪliənt/)', max_length=100, null=True),
        ),
    ]
