# Generated by Django 5.1.7 on 2025-07-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0013_add_favorite_flashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='study_mode',
            field=models.CharField(choices=[('deck', 'Deck Study'), ('random', 'Random Study'), ('favorites', 'Favorites Study'), ('spaced_repetition', 'Spaced Repetition')], default='deck', max_length=20),
        ),
    ]
