# Generated by Claude Code for performance optimization

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0014_add_favorites_study_mode'),
    ]

    operations = [
        # Add indexes for difficulty-based card selection
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_flashcard_difficulty_user ON vocabulary_flashcard(user_id, difficulty_score);",
            reverse_sql="DROP INDEX IF EXISTS idx_flashcard_difficulty_user;"
        ),
        
        # Add index for daily reset logic
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_flashcard_daily_tracking ON vocabulary_flashcard(user_id, last_seen_date, times_seen_today);",
            reverse_sql="DROP INDEX IF EXISTS idx_flashcard_daily_tracking;"
        ),
        
        # Add index for study session queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_flashcard_study_filter ON vocabulary_flashcard(user_id, deck_id, difficulty_score) WHERE difficulty_score IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_flashcard_study_filter;"
        ),
        
        # Add index for statistics queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_studysessionanswer_user_date ON vocabulary_studysessionanswer(flashcard_id, answered_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_studysessionanswer_user_date;"
        ),
        
        # Add partial index for active incorrect words
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_incorrectwordreview_active ON vocabulary_incorrectwordreview(user_id, question_type) WHERE is_resolved = FALSE;",
            reverse_sql="DROP INDEX IF EXISTS idx_incorrectwordreview_active;"
        ),
        
        # Add index for deck-based filtering
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_flashcard_deck_difficulty ON vocabulary_flashcard(deck_id, difficulty_score) WHERE difficulty_score IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_flashcard_deck_difficulty;"
        ),
    ]