# Generated by Django 5.1.7 on 2025-09-04 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0015_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', 'created_at'], name='vocabulary__user_id_11ef79_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', 'name'], name='vocabulary__user_id_4b9f80_idx'),
        ),
        migrations.AddIndex(
            model_name='definition',
            index=models.Index(fields=['flashcard'], name='vocabulary__flashca_f89090_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'word'], name='vocabulary__user_id_862c46_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'deck'], name='vocabulary__user_id_59ee66_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'last_seen_date'], name='vocabulary__user_id_482a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'difficulty_score'], name='vocabulary__user_id_67a049_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'times_seen_today'], name='vocabulary__user_id_d6ba5b_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'created_at'], name='vocabulary__user_id_b34c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['difficulty_score', 'times_seen_today'], name='vocabulary__difficu_cdc345_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['last_seen_date', 'times_seen_today'], name='vocabulary__last_se_cdd719_idx'),
        ),
    ]
