# Generated by Django 5.2.1 on 2025-09-09 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0016_optimize_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistFlashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_by",
                        to="vocabulary.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_flashcards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-blacklisted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "blacklisted_at"],
                        name="vocabulary__user_id_c2f550_idx",
                    ),
                    models.Index(
                        fields=["user", "flashcard"],
                        name="vocabulary__user_id_4c04fd_idx",
                    ),
                ],
                "unique_together": {("user", "flashcard")},
            },
        ),
    ]
