# Generated by Django 5.1.7 on 2025-09-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0017_blacklistflashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='cefr_level',
            field=models.CharField(blank=True, help_text='CEFR level (A1, A2, B1, B2, C1, C2)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='cefr_level_auto',
            field=models.BooleanField(default=False, help_text='Whether CEFR level was automatically determined'),
        ),
    ]
