# Generated by Django 5.2.1 on 2026-05-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0018_add_cefr_level_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='example_sentence',
            field=models.TextField(blank=True, help_text='Example sentence showing word in context', null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='example_source',
            field=models.CharField(blank=True, help_text="Source: 'cambridge', 'llm', or 'manual'", max_length=10, null=True),
        ),
    ]
